import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { toPage } from './lib.mjs';
const require = createRequire('/home/user/awaketab/node_modules/.pnpm/playwright@1.63.0/node_modules/playwright/');
const { chromium } = require('playwright');
const [file, props, sel] = [process.argv[2], JSON.parse(process.argv[3]), process.argv[4].split(',')];
const { page: html } = toPage(file, props);
const tmp = new URL('./.m.html', import.meta.url); writeFileSync(tmp, html);
const b = await chromium.launch(); const pg = await b.newPage({ viewport: { width: 1280, height: 900 } });
await pg.goto(tmp.href); await pg.waitForTimeout(500);
for (const s of sel) console.log(s, JSON.stringify(await pg.evaluate((s) => { const e = document.querySelector(s); if (!e) return null; const r = e.getBoundingClientRect(); return { x: r.x, y: r.y, w: r.width, h: r.height }; }, s)));
if (process.argv[5]) await pg.screenshot({ path: process.argv[5], fullPage: true });
await b.close();
