import type { ILocaleHomeCopy } from './types';

export const de: ILocaleHomeCopy = {
  whatItDoes: [
    'AwakeTab nutzt die Wake-Lock-API des Browsers, solange dieser Tab sichtbar ist, und die Statusanzeige meldet erst dann, dass der Bildschirm eingeschaltet bleibt, wenn der Browser den Lock tatsächlich bestätigt hat. Wählen Sie eine Dauer (15 Minuten bis 4 Stunden, eine benutzerdefinierte Länge von bis zu sieben Tagen oder eine Uhrzeit), und der Bildschirm wird nicht mehr dunkel und schläft nicht ein (eine Sperrrichtlinie Ihrer Firma kann ihn trotzdem sperren). Die Anzeige zeigt „Bildschirm bleibt an“ nur, solange der Browser den Lock tatsächlich hält. Blenden Sie diesen Tab aus, nimmt der Browser den Lock zurück, die Anzeige wechselt zu „Pausiert — Tab ausgeblendet“, und der Timer stoppt, bis Sie zurückkehren.',
    'Es ist kein Konto, kein Download und keine Erweiterung nötig: Das gesamte Tool ist diese Seite. Einstellungen, die aktuelle Sitzung und sieben Tage Statistik bleiben in diesem Browser. Auf der Website sind anonyme Nutzungsdaten standardmäßig eingeschaltet, ohne Cookies und ohne Kennungen; Sie können sie in den Einstellungen abschalten. Diese Seite lädt keine Skripte oder Web-Fonts von Drittanbietern, bleibt daher auch auf dem Smartphone schnell und funktioniert nach dem ersten Besuch offline. Die Kopfzeile bietet eine Installationsoption, falls Sie das Tool auf dem Startbildschirm oder im Dock ablegen möchten; die installierte App kann beim Ende einer Sitzung einen Ton abspielen und benachrichtigen.',
  ],
  howItWorks: [
    'Sie wählen eine Dauer. Eine Voreinstellung, eine benutzerdefinierte Länge oder eine Uhrzeit startet eine Sitzung. Dieselben Optionen erreichen Sie auch per Tastendruck: 1 bis 6 für Voreinstellungen, 0 für kein Ende, U für eine Uhrzeit und die Leertaste zum Starten oder Beenden.',
    'Der Browser wird um einen Screen Wake Lock gebeten. AwakeTab ruft die Screen Wake Lock API auf — denselben Mechanismus, den auch ein Videoplayer nutzt. Der Browser kann zustimmen, ablehnen oder den Lock später zurücknehmen; alle drei Antworten werden angezeigt, sobald sie eintreten.',
    'Der Timer folgt dem Lock, nicht der Uhr. Der Countdown läuft nur, solange der Lock gehalten wird, und jede Berechnung nutzt die Systemzeit, sodass ein Laptop, der in den Ruhezustand versetzt wurde, mit einer ehrlichen Zahl zurückkehrt. Ist die Zeit abgelaufen, ertönt ein Signal, und Sie können verlängern oder beenden.',
  ],
  honestLimits: [
    'Ein ausgeblendeter Tab kann keinen Wake Lock halten. Das Wechseln der App, das Minimieren oder ein Tab-Wechsel pausiert die Sitzung. Das ist eine Plattformregel. Damit der Bildschirm auch hinter anderen Fenstern eingeschaltet bleibt, nutzen Sie die AwakeTab-Erweiterung für Chrome und Edge.',
    'Das Schließen des Laptop-Deckels versetzt das Gerät weiterhin in den Ruhezustand. Keine Webseite und keine Erweiterung kann das ändern. Dafür braucht es eine Betriebssystem-Einstellung, einen externen Bildschirm oder ein natives Tool.',
    'Energiesparfunktionen können den Bildschirm trotzdem dimmen oder sperren. Der Stromsparmodus des iPhone stellt die automatische Sperre auf 30 Sekunden, und Firefox gibt den Lock bei 5 % Akku auf. Lehnt ein Browser ab, zeigt die Anzeige „Blockiert — so beheben Sie es“ und nennt die Ursache.',
    'Ihren Chat-Status beeinflusst es nicht. Die Anwesenheitsanzeige von Teams, Slack und Zoom richtet sich nach der Leerlaufzeit von Tastatur und Maus, nicht nach dem Bildschirm. Ein Wake Lock hält Sie nicht „grün“, und AwakeTab simuliert niemals Eingaben, um das vorzutäuschen.',
    'Bildschirm-Ruhezustand ist nicht dasselbe wie System-Ruhezustand. Ein Wake Lock hält den Bildschirm an. In Chrome und Edge unter Windows und macOS hält das auch den Computer vom Leerlauf-Ruhezustand ab, solange der Tab sichtbar ist. Mit zugeklapptem Deckel schläft ein Laptop trotzdem ein. Damit der Computer bei ausgeschaltetem Bildschirm wach bleibt, nutzen Sie ein natives Dienstprogramm oder die Stufe „System“ der Erweiterung.',
    'Andere Software folgt ihren eigenen Regeln. Eine Bank-Abmeldung, eine Prüfungsaufsicht-App, ein Monitor, der bei Signalverlust in den Ruhezustand geht, oder eine unternehmensweite Sperrbildschirm-Richtlinie liegen alle außerhalb der Reichweite eines Wake Locks.',
  ],
};
