import type { ILocaleHomeCopy } from './types';

export const fr: ILocaleHomeCopy = {
  whatItDoes: [
    'AwakeTab utilise l’API Wake Lock du navigateur tant que cet onglet est visible, et le statut n’affirme l’éveil qu’après confirmation du navigateur. Choisissez une durée (de 15 minutes à 4 heures, une durée personnalisée allant jusqu’à sept jours, ou une heure précise) et l’écran cesse de s’assombrir et de se mettre en veille (une politique de verrouillage d’entreprise peut toutefois le verrouiller). La pastille affiche Écran allumé uniquement lorsque le navigateur détient réellement le verrou. Masquez cet onglet et le navigateur reprend le verrou : la pastille passe alors à En pause — onglet masqué et le minuteur s’arrête jusqu’à votre retour.',
    'Aucun compte, aucun téléchargement et aucune extension ne sont nécessaires : l’outil, c’est cette page. Les réglages, la session en cours et sept jours de statistiques restent dans ce navigateur. Sur le site, des données d’utilisation anonymes sont envoyées par défaut, sans cookies ni identifiants ; vous pouvez les désactiver dans les Paramètres. Cette page ne charge aucun script tiers ni aucune police web, ce qui la garde rapide sur téléphone et lui permet de fonctionner hors ligne après la première visite. L’en-tête propose une option d’installation si vous la voulez sur un écran d’accueil ou un dock ; l’application installée peut alors jouer un carillon et vous avertir lorsqu’une session se termine.',
  ],
  howItWorks: [
    'Vous choisissez une durée. Une durée prédéfinie, une durée personnalisée ou une heure précise démarre une session. Les mêmes choix tiennent en une touche : 1 à 6 pour les durées prédéfinies, 0 pour aucune heure de fin, U pour une heure précise et Espace pour démarrer ou arrêter.',
    'Le navigateur est sollicité pour un verrou d’éveil d’écran. AwakeTab appelle la Screen Wake Lock API — le même mécanisme qu’utilise un lecteur vidéo. Le navigateur peut accepter, refuser ou reprendre le verrou plus tard ; ces trois réponses sont affichées au fur et à mesure qu’elles surviennent.',
    'Le minuteur suit le verrou, pas l’horloge. Le compte à rebours ne s’écoule que pendant que le verrou est détenu, et chaque calcul s’appuie sur l’heure système, si bien qu’un ordinateur portable mis en veille prolongée retrouve un chiffre honnête à son réveil. Une fois le temps écoulé, un carillon retentit et vous pouvez choisir de prolonger ou d’arrêter.',
  ],
  honestLimits: [
    'Un onglet masqué ne peut pas détenir de verrou d’éveil. Changer d’application, réduire la fenêtre ou changer d’onglet met la session en pause. C’est une règle imposée par la plateforme. Pour garder l’écran allumé derrière d’autres fenêtres, utilisez l’extension AwakeTab pour Chrome et Edge.',
    'Fermer le capot met tout de même l’ordinateur en veille. Aucune page web ni extension ne peut changer cela. Il faut un réglage du système d’exploitation, un écran externe ou un outil natif.',
    'Les économies d’énergie peuvent encore assombrir ou verrouiller l’écran. Le mode Économie d’énergie de l’iPhone règle le verrouillage automatique sur 30 secondes, et Firefox rend le verrou à 5 % de batterie. Quand un navigateur refuse, la pastille affiche Bloqué — voici la solution et nomme la cause.',
    'Cela ne touche pas votre statut de présence. La présence sur Teams, Slack et Zoom suit l’inactivité du clavier et de la souris, pas l’état de l’écran. Un verrou d’éveil ne vous maintiendra pas « disponible », et AwakeTab ne simule jamais de frappe ni de mouvement de souris pour le falsifier.',
    'La veille de l’écran n’est pas la veille du système. Un verrou d’éveil garde l’écran allumé. Dans Chrome et Edge sous Windows et macOS, il empêche aussi la mise en veille pour inactivité de l’ordinateur tant que l’onglet est visible. Un capot fermé met quand même l’ordinateur en veille. Pour le garder éveillé écran éteint, utilisez un outil natif ou le niveau Système de l’extension.',
    'Les autres logiciels gardent leurs propres règles. Une déconnexion bancaire, une application de surveillance d’examen, un moniteur qui s’éteint en cas de perte de signal ou une politique de verrouillage d’écran d’entreprise échappent tous à la portée d’un verrou d’éveil.',
  ],
};
