import { readFileSync, readdirSync } from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire('/Users/soubhik/Work/github/awaketab/package.json');
const { chromium } = require('/Users/soubhik/Work/github/awaketab/node_modules/.pnpm/playwright@1.63.0/node_modules/playwright');
const DIR = '/private/tmp/claude-501/-Users-soubhik-Work-github-awaketab/68604392-2b5c-4388-8fa5-e0e1d91d7184/scratchpad/directions/project/';
const [file, props, W, H, sel] = process.argv.slice(2);
const files = {}; for (const f of readdirSync(DIR)) if (f.endsWith('.dc.html')) files[f.replace('.dc.html', '')] = readFileSync(DIR + f, 'utf8');
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: +W, height: +H } });
await p.setContent('<!doctype html><html><head></head><body style="margin:0"></body></html>');
await p.addScriptTag({ content: readFileSync(new URL('./inpage.js', import.meta.url), 'utf8') });
await p.evaluate(({ files, n, pr }) => window.__render(files, n, pr), { files, n: file, pr: JSON.parse(props) });
await p.addStyleTag({ content: '*{animation:none!important;transition:none!important}' });
await p.evaluate(() => document.fonts.ready); await p.waitForTimeout(300);
console.log(await p.evaluate((sel) => [...document.querySelectorAll(sel)].map((e) => Math.round(e.getBoundingClientRect().top) + ' ' + e.tagName + ' ' + e.textContent.trim().slice(0, 50)).join('\n'), sel));
await b.close();
