import { chromium } from 'playwright';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const dir = process.env.RT_DIR || '/private/tmp/claude-501/-Users-soubhik-Work-github-awaketab/68604392-2b5c-4388-8fa5-e0e1d91d7184/scratchpad/rtsrv';
const canvas = JSON.parse(fs.readFileSync('/Users/soubhik/Work/github/awaketab/design/canvas/project/canvas.json','utf8'));
const srv = http.createServer((q, r) => { const f = path.join(dir, decodeURIComponent(q.url.split('?')[0])); if (!fs.existsSync(f)) { r.writeHead(404); return r.end(); } r.writeHead(200, { 'content-type': f.endsWith('.js') ? 'text/javascript' : 'text/html' }); fs.createReadStream(f).pipe(r); }).listen(Number(process.env.RT_PORT||8766));
const b = await chromium.launch(); const out = [];
const only = process.argv.slice(2); const files = only.length ? only.map(f => [f, canvas.boards[f] || (() => { const m = /width:\s*(\d+)px;\s*height:\s*(\d+)px/.exec(fs.readFileSync(path.join(dir, f), 'utf8')) || [0, 1280, 2000]; return { w: +m[1], h: +m[2] }; })()]) : Object.entries(canvas.boards);
const worker = async (list) => { const pg = await b.newPage();
  for (const [f, bd] of list) { const errs = [];
    pg.removeAllListeners('pageerror'); pg.removeAllListeners('console');
    pg.on('pageerror', e => errs.push(String(e).slice(0,200))); pg.on('console', m => { if (m.type()==='error') errs.push(m.text().slice(0,200)); });
    await pg.setViewportSize({ width: Math.min(bd.w, 4000), height: Math.min(bd.h, 8000) });
    await pg.goto('http://localhost:' + (process.env.RT_PORT||8766) + '/' + f, { waitUntil: 'load' }).catch(e => errs.push('goto '+e));
    await pg.waitForTimeout(1200);
    const i = await pg.evaluate(() => { const r = document.body.getBoundingClientRect(); return { nodes: document.body.querySelectorAll('*').length, text: document.body.innerText.trim().length, h: Math.round(document.documentElement.scrollHeight), w: Math.round(document.documentElement.scrollWidth) }; });
    out.push({ f, ...i, bw: bd.w, bh: bd.h, errs: [...new Set(errs)].filter(e => !e.includes('{{')).slice(0,3) });
  } await pg.close(); };
const n = 6, chunks = Array.from({ length: n }, (_, k) => files.filter((_, j) => j % n === k));
await Promise.all(chunks.map(worker));
await b.close(); srv.close();
fs.writeFileSync(path.join(dir, 'scan.json'), JSON.stringify(out, null, 1));
const bad = out.filter(o => o.nodes < 40 || o.text < 20 || o.errs.length || o.w > o.bw + 2);
console.log('scanned', out.length, 'flagged', bad.length);
for (const o of bad) console.log(o.f, 'nodes', o.nodes, 'text', o.text, 'w', o.w, '/', o.bw, o.errs.join(' | '));
