// node GuideShot.mjs File.dc.html layout theme chunkHeight [propsJson] [patchJson] -> shots/gs-<name>-<layout>-<theme>-<n>.png
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { load, toHtml } from './ProLib.mjs';
const require = createRequire('/Users/soubhik/Work/github/awaketab/node_modules/.pnpm/playwright@1.63.0/node_modules/playwright/');
const { chromium } = require('playwright');
const [file, layout, theme, chunk = '1100', props = '{}', patch = '{}'] = process.argv.slice(2);
const { Component } = load(file);
const c = new Component(Object.assign({ layout, theme }, JSON.parse(props)));
Object.assign(c.state, JSON.parse(patch));
const vals = c.renderVals();
const tmp = new URL('./.gs-render.html', import.meta.url);
writeFileSync(tmp, toHtml(file, vals));
const w = parseInt(vals.W, 10);
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: w, height: 900 }, colorScheme: theme === 'light' ? 'light' : 'dark' });
await page.goto(tmp.href);
await page.waitForTimeout(700);
const h = await page.evaluate(() => Math.ceil(document.querySelector('.at-root').getBoundingClientRect().height));
await page.setViewportSize({ width: w, height: h });
const ch = parseInt(chunk, 10);
let n = 0;
for (let y = 0; y < h; y += ch, n++) await page.screenshot({ path: new URL(`./shots/gs-${file.replace('.dc.html', '')}-${layout}-${theme}-${n}.png`, import.meta.url).pathname, clip: { x: 0, y, width: w, height: Math.min(ch, h - y) } });
console.log(file, layout, theme, 'height', h, 'chunks', n);
await browser.close();
