import { readFileSync } from 'node:fs';
const { chromium } = await import('/Users/soubhik/Work/github/awaketab/node_modules/.pnpm/playwright@1.63.0/node_modules/playwright/index.mjs');
const src = readFileSync(new URL('../../directions/project/Intl.dc.html', import.meta.url), 'utf8');
const L = JSON.parse(src.match(/\/\*L10N\*\/([\s\S]*?)\/\*END\*\//)[1]);
const b = await chromium.launch(); const p = await b.newPage();
await p.setContent('<html><head><link href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600&family=Noto+Sans+JP:wght@400;500;600&family=Noto+Sans+SC:wght@400;500;600&family=Noto+Sans+Devanagari:wght@400;500;600&display=swap" rel="stylesheet"></head><body></body></html>');
const fonts = { ja: "Geist, 'Hiragino Sans', 'Noto Sans JP', sans-serif", zh: "Geist, 'PingFang SC', 'Noto Sans SC', sans-serif", hi: "Geist, 'Kohinoor Devanagari', 'Noto Sans Devanagari', sans-serif" };
const rows = [];
for (const [c, v] of Object.entries(L)) for (const key of Object.keys(v.s).filter((k) => /^tool\.pill\.|tool\.ring\.start/.test(k))) rows.push([c, key, v.s[key], key === 'tool.ring.start' ? 17 : 15, fonts[c] || 'Geist, sans-serif']);
const out = await p.evaluate(async (rows) => { await new Promise((r) => setTimeout(r, 1500)); await document.fonts.ready; return rows.map(([c, k, s, px, ff]) => { const e = document.createElement('span'); e.style.cssText = `font: 600 ${px}px ${ff}; white-space: nowrap`; e.textContent = s; document.body.appendChild(e); const w = e.getBoundingClientRect().width; e.remove(); return [c, k, Math.round(w), s]; }); }, rows);
for (const r of out) if (r[2] > 200) console.log(r.join(' | '));
await b.close();
